### PR TITLE
Comments moveapps

### PR DESCRIPTION
**Pull request by annescharf**
Hi @jmsigner and @marcosci, I tiried running the app locally with the co-pilot-sdk.R and I get the error:
`Warning in dir.create(targetDirUDs <- tempdir()) :
  '/tmp/RtmpX8rcDj' already exists`
 `Error in : [writeStart] file exists. You can use 'overwrite=TRUE' to overwrite it` 

Going though the code, maybe the problem could be in L69, were a tem folder is created, but then used twice in L72 and L76.
And looking at the code, I think in L72 the `appArtifactPath` is missing right?

I guess you can merge this branch, and once the code is adjusted I'll have a second look. Thanks!

### CODE REVIEW

**Comment by jmsigner** [comment]
Thanks @andreakoelzsch for the updates in the documentation. @annescharf the problem should be fixed now.

**Comment by annescharf** [comment]
@jmsigner unfortunately I still cannot run the app. Did you check that it runs with the `co-pilot-sdk.R`? If not, I highly recommend you to do so, its the only way to know it will run as expected on moveapps before submitting it. The error I get is:

`Caused by error in `input$isopleth_levels`:   `
`! Can't access reactive value 'isopleth_levels' outside of reactive consumer.    `
`ℹ Do you need to wrap inside reactive() or observe()?`

**Comment by jmsigner** [comment]
@annescharf strange, it did work on my end using the `co-pilot-sdk.R`  yesterday, I will look into it again.

**Comment by annescharf** [comment]
@jmsigner , hmm that's strange....This is the content of the error.log file. Maybe it helps to locate the potential problem easier.

```
[1m[33mError[39m in `map()` at ]8;line = 61:col = 2;file:///home/ascharf/AllGitSYNC/MoveAppsGit/moveapps_ctmm_akde/ShinyModule.RShinyModule.R:61:2]8;;:[22m
[38;5;255m[36mℹ[38;5;255m In index: 1.
[36mℹ[38;5;255m With name: Cilla.[39m
[1mCaused by error in `input$isopleth_levels`:[22m
[33m![39m Can't access reactive value 'isopleth_levels' outside of reactive consumer.
[34mℹ[39m Do you need to wrap inside reactive() or observe()?

```

**Comment by jmsigner** [comment]
@annescharf I think I found the error and hopefully fixed it with the latest commit.

**Comment by annescharf** [comment]
@jmsigner, now it works thanks! I am aware that managing the outlay of leaflet can be a pain, and not everything can be done as one would wish. But I'll anyway point out what I see that could be improvable:
- unselecting the last individual (in this case "Toni") is not possible, I guess because of the "zoom full" button
- everytime the isopleth level is changed, all individuals are again selected and it zooms out to the full extent. If one wants to look at e.g. the changes in size of the HR of one individual, it takes a loot of clicking and remembering how it just looked at another isopleph level
- the 2 legends on the right are overlapping, so if all individuals are selected the "zoom into individual X" buttons go under(are not really visible). Also if more than 4 individuals are selected, the remaining are not shown.

**Comment by jmsigner** [comment]
@annescharf, I reworked the whole map and I think most issues are solved. I haven't figured out how to do the colors properly, currently they are all black. Should users be able to select animals separately?

**Comment by annescharf** [comment]
@jmsigner , great! Followup suggestions: maybe put all 3 sliders/input box into one line, so there is more space for the map, to make it as large as possible. If you want, have a look at `shinycssloaders::withSpinner` it gives the user the feeling that something is happening when the map takes a while to load. 

not sure if I understand your last question, as the animal can be currently selected/unselected...

I guess black is ok, would be awesome if each indiv could get a different color, or something. The old legend from the colors is still in there...

Remember to add the new setting possibilities to the README :) 

Thanks!

**Comment by jmsigner** [comment]
Hi @annescharf, great comments, thanks. Sorry, I was not really clear about the selection of animals. I thought it would be useful to have the option to remove/add all animals at once. I now added a button to remove all animals at once and they can then be added individually. I also added a spinner, colors and rearranged the input and updated the documentation.

**Comment by annescharf** [comment]
Hi @jmsigner , it looks great! 
one thing, just in case you haven't noticed it happening. So each time one of the sliders is used, a new box "Full extent" appears on the left side. After some clicks I have them covering the entire side. Nothing dramatic, just maybe worth fixing at some point

**Pull request merged**
